### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by mdrijwan123** [jelmerk/hnswlib-spark#2]
Hey Thankyou for this spark integration.
I am getting one issue as I am trying to run this on databricks and I am getting above error:
I am installing packages and using module as:
```
%pip install pyspark-hnsw==1.1.0 findspark
hnsw = HnswSimilarity(identifierCol='product_id', queryIdentifierCol='user_id', featuresCol='Embedding_items',
                      distanceFunction='cosine', numPartitions=10, excludeSelf=True, k = 10)
```

Running above I am getting below error:
**TypeError: 'JavaPackage' object is not callable**

I am using spark: 3.4.1 and using DBR 13.3 LTS.
But above code running good in Colab. Please let me know if you have some information for fix. Thankyou.

**Comment by jelmerk** [comment]
Check which version of scala your databricks runtime uses

<img width="355" alt="image" src="https://github.com/jelmerk/hnswlib-spark/assets/133639/5907292a-0fcd-4c46-a8ea-8d33bb78f359">

Then add the correct version of hnsw  to your cluster libraries

<img width="1321" alt="image" src="https://github.com/jelmerk/hnswlib-spark/assets/133639/8c041b05-f537-4645-9106-6013bf053471">

You don't even have to pip install the module

**Comment by mdrijwan123** [comment]
Awesome, Thankyou so much.
